import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import load_config

logger = logging.getLogger(__name__)


def _get_smtp_config():
    """Load SMTP settings from config. Returns a dict or None if disabled."""
    config = load_config()
    if not config.get("email_notifications_enabled"):
        return None
    host = config.get("smtp_host", "").strip()
    recipient = config.get("notification_email", "").strip()
    if not host or not recipient:
        return None
    return {
        "host": host,
        "port": int(config.get("smtp_port", 587)),
        "username": config.get("smtp_username", ""),
        "password": config.get("smtp_password", ""),
        "use_tls": config.get("smtp_use_tls", True),
        "recipient": recipient,
    }


def _build_email_html(title, article_url, data):
    """Build an inline-CSS HTML email body from structured summary data."""
    executive_summary = data.get("executive_summary", "No summary available.")
    novelty = data.get("novelty", "Nothing particularly novel reported.")
    details = data.get("details", [])
    mitigations = data.get("mitigations", [])

    details_html = "".join(f"<li style=\"margin-bottom:6px;\">{_esc(d)}</li>" for d in details)
    mitigations_html = "".join(f"<li style=\"margin-bottom:6px;\">{_esc(m)}</li>" for m in mitigations)

    source_html = ""
    if article_url:
        source_html = (
            f'<table style="width:100%;margin-bottom:20px;border-collapse:collapse;">'
            f'<tr><td style="padding:10px 14px;background:#f0f4f8;border-left:4px solid #4a90d9;border-radius:4px;font-size:13px;color:#555;">'
            f'<strong style="color:#333;">Source:</strong> '
            f'<a href="{_esc(article_url)}" style="color:#4a90d9;word-break:break-all;">{_esc(article_url)}</a>'
            f'</td></tr></table>'
        )

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,Helvetica,sans-serif;color:#222;background:#f5f5f5;padding:20px;">
<div style="max-width:640px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #ddd;">
  <div style="background:#1a1a2e;color:#fff;padding:16px 24px;">
    <h1 style="margin:0;font-size:18px;">Threat Loom Alert</h1>
  </div>
  <div style="padding:24px;">
    <h2 style="margin:0 0 12px;font-size:16px;color:#1a1a2e;">{_esc(title)}</h2>
    {source_html}

    <h3 style="color:#1a1a2e;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">Executive Summary</h3>
    <p style="line-height:1.6;">{_esc(executive_summary)}</p>

    <h3 style="color:#1a1a2e;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">Novelty</h3>
    <p style="line-height:1.6;">{_esc(novelty)}</p>

    <h3 style="color:#1a1a2e;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">Details</h3>
    <ul style="line-height:1.6;padding-left:20px;">{details_html if details_html else '<li>No details available.</li>'}</ul>

    <h3 style="color:#1a1a2e;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">Mitigations</h3>
    <ul style="line-height:1.6;padding-left:20px;">{mitigations_html if mitigations_html else '<li>No mitigations listed.</li>'}</ul>

    <hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
    <p style="font-size:12px;color:#999;">This alert was generated by Threat Loom.</p>
    <p style="font-size:11px;color:#b0b0b0;line-height:1.5;margin-top:8px;">Disclaimer: This summary was generated by Threat Loom using large language models (LLMs). LLMs can make mistakes. Always verify important information against the original source.</p>
  </div>
</div>
</body>
</html>"""


def _esc(text):
    """Escape HTML special characters."""
    if not text:
        return ""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _send_email(smtp_cfg, subject, html_body):
    """Send an email via SMTP. Returns (success, error_msg)."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_cfg["username"] or smtp_cfg["recipient"]
    msg["To"] = smtp_cfg["recipient"]
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        server = smtplib.SMTP(smtp_cfg["host"], smtp_cfg["port"], timeout=15)
        try:
            if smtp_cfg["use_tls"]:
                server.starttls()
            if smtp_cfg["username"] and smtp_cfg["password"]:
                server.login(smtp_cfg["username"], smtp_cfg["password"])
            server.sendmail(msg["From"], [smtp_cfg["recipient"]], msg.as_string())
        finally:
            server.quit()
        return True, None
    except Exception as e:
        return False, str(e)


def send_article_notification(title, article_url, raw_data):
    """Send an email notification for a newly summarized article.

    Errors are logged but never raised so the pipeline is not blocked.
    """
    smtp_cfg = _get_smtp_config()
    if smtp_cfg is None:
        return

    html = _build_email_html(title, article_url, raw_data)
    subject = f"Threat Loom: {title}"
    ok, err = _send_email(smtp_cfg, subject, html)
    if ok:
        logger.info(f"Email notification sent for: {title[:60]}")
    else:
        logger.error(f"Email notification failed for '{title[:60]}': {err}")


def send_report_email(report_type: str, identifier: str, llm_content: str,
                      metadata: dict, user_note: str):
    """Send a developer report email for an LLM output.
    Returns (success, error_msg).
    """
    smtp_cfg = _get_smtp_config()
    if smtp_cfg is None:
        return False, "SMTP not configured"

    subject = f"[Threat Loom Report] {report_type} — {identifier[:80]}"
    meta_rows = "".join(
        f"<tr><td style='padding:4px 8px;font-weight:bold;color:#555;'>{_esc(k)}</td>"
        f"<td style='padding:4px 8px;'>{_esc(str(v))}</td></tr>"
        for k, v in metadata.items()
    )
    note_section = (
        f"<h3 style='color:#1a1a2e;'>User Note</h3>"
        f"<p style='background:#fffbe6;padding:10px;border-left:4px solid #f0b429;'>{_esc(user_note)}</p>"
        if user_note.strip() else ""
    )
    html = f"""<!DOCTYPE html><html><body style='font-family:Arial,sans-serif;background:#f5f5f5;padding:20px;'>
<div style='max-width:680px;margin:0 auto;background:#fff;border-radius:8px;border:1px solid #ddd;'>
  <div style='background:#1a1a2e;color:#fff;padding:16px 24px;'>
    <h1 style='margin:0;font-size:18px;'>Threat Loom — LLM Output Report</h1>
  </div>
  <div style='padding:24px;'>
    <h2 style='color:#1a1a2e;font-size:16px;margin-bottom:12px;'>{_esc(report_type)}: {_esc(identifier)}</h2>
    <table style='border-collapse:collapse;width:100%;margin-bottom:16px;font-size:13px;background:#f9f9f9;'>
      {meta_rows}
    </table>
    {note_section}
    <h3 style='color:#1a1a2e;'>LLM Output (auto-captured)</h3>
    <pre style='background:#f5f5f5;padding:14px;border-radius:4px;white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:1.5;'>{_esc(llm_content)}</pre>
    <p style='font-size:11px;color:#999;margin-top:20px;'>Auto-generated by Threat Loom Android app. LLM content was not editable by the user.</p>
  </div>
</div></body></html>"""
    return _send_email(smtp_cfg, subject, html)


def send_test_email(smtp_cfg=None):
    """Send a test email using dummy data. Returns (success, error_msg).

    Args:
        smtp_cfg: Optional SMTP config dict. If None, loads from saved config.
    """
    if smtp_cfg is None:
        smtp_cfg = _get_smtp_config()
    if smtp_cfg is None:
        return False, "Email notifications are not configured. Enable notifications and fill in SMTP settings."

    dummy_data = {
        "executive_summary": (
            "This is a test notification from Threat Loom. If you are reading this, "
            "your email notification settings are configured correctly."
        ),
        "novelty": "No novel threat activity — this is only a test.",
        "details": [
            "SMTP connection to your mail server was successful.",
            "Email rendering and delivery are working as expected.",
        ],
        "mitigations": [
            "No action required — this is a test notification.",
        ],
    }

    html = _build_email_html("Test Notification", "", dummy_data)
    return _send_email(smtp_cfg, "Threat Loom: Test Notification", html)
