package com.threatloom.app.domain.category

/**
 * MITRE ATT&CK entity data for sub-category validation.
 * Source: enterprise-attack-18.1.json
 * Auto-ported from mitre_data.py
 */
object MitreData {

    private fun normalize(name: String): String = name.trim().lowercase().replace(" ", "-")

    private fun buildLookup(data: List<Pair<String, List<String>>>): Map<String, String> {
        val lookup = mutableMapOf<String, String>()
        for ((primary, aliases) in data) {
            val tag = normalize(primary)
            lookup[tag] = primary
            for (alias in aliases) {
                val atag = normalize(alias)
                if (atag.isNotEmpty() && atag != tag) {
                    lookup[atag] = primary
                }
            }
        }
        return lookup
    }

    private val threatActorData = listOf(
        "admin@338" to emptyList(),
        "Agrius" to listOf("Pink Sandstorm", "AMERICIUM", "Agonizing Serpens", "BlackShadow"),
        "Ajax Security Team" to listOf("Operation Woolen-Goldfish", "AjaxTM", "Rocket Kitten", "Flying Kitten", "Operation Saffron Rose"),
        "Akira" to listOf("GOLD SAHARA", "PUNK SPIDER", "Howling Scorpius"),
        "Andariel" to listOf("Silent Chollima", "PLUTONIUM", "Onyx Sleet"),
        "Aoqin Dragon" to emptyList(),
        "AppleJeus" to listOf("Gleaming Pisces", "Citrine Sleet", "UNC1720", "UNC4736"),
        "APT-C-23" to listOf("Mantis", "Arid Viper", "Desert Falcon", "TAG-63", "Grey Karkadann", "Big Bang APT", "Two-tailed Scorpion"),
        "APT-C-36" to listOf("Blind Eagle"),
        "APT1" to listOf("Comment Crew", "Comment Group", "Comment Panda"),
        "APT12" to listOf("IXESHE", "DynCalc", "Numbered Panda", "DNSCALC"),
        "APT16" to emptyList(),
        "APT17" to listOf("Deputy Dog"),
        "APT18" to listOf("TG-0416", "Dynamite Panda", "Threat Group-0416"),
        "APT19" to listOf("Codoso", "C0d0so0", "Codoso Team", "Sunshop Group"),
        "APT28" to listOf("IRON TWILIGHT", "SNAKEMACKEREL", "Swallowtail", "Group 74", "Sednit", "Sofacy", "Pawn Storm", "Fancy Bear", "STRONTIUM", "Tsar Team", "Threat Group-4127", "TG-4127", "Forest Blizzard", "FROZENLAKE", "GruesomeLarch"),
        "APT29" to listOf("IRON RITUAL", "IRON HEMLOCK", "NobleBaron", "Dark Halo", "NOBELIUM", "UNC2452", "YTTRIUM", "The Dukes", "Cozy Bear", "CozyDuke", "SolarStorm", "Blue Kitsune", "UNC3524", "Midnight Blizzard"),
        "APT3" to listOf("Gothic Panda", "Pirpi", "UPS Team", "Buckeye", "Threat Group-0110", "TG-0110"),
        "APT30" to emptyList(),
        "APT32" to listOf("SeaLotus", "OceanLotus", "APT-C-00", "Canvas Cyclone", "BISMUTH"),
        "APT33" to listOf("HOLMIUM", "Elfin", "Peach Sandstorm"),
        "APT37" to listOf("InkySquid", "ScarCruft", "Reaper", "Group123", "TEMP.Reaper", "Ricochet Chollima"),
        "APT38" to listOf("NICKEL GLADSTONE", "BeagleBoyz", "Bluenoroff", "Stardust Chollima", "Sapphire Sleet", "COPERNICIUM"),
        "APT39" to listOf("ITG07", "Chafer", "Remix Kitten"),
        "APT41" to listOf("Wicked Panda", "Brass Typhoon", "BARIUM"),
        "APT42" to emptyList(),
        "APT5" to listOf("Mulberry Typhoon", "MANGANESE", "BRONZE FLEETWOOD", "Keyhole Panda", "UNC2630"),
        "Aquatic Panda" to emptyList(),
        "Axiom" to listOf("Group 72"),
        "BackdoorDiplomacy" to emptyList(),
        "BITTER" to listOf("T-APT-17"),
        "BlackByte" to listOf("Hecamede"),
        "BlackOasis" to emptyList(),
        "BlackTech" to listOf("Palmerworm"),
        "Blue Mockingbird" to emptyList(),
        "BRONZE BUTLER" to listOf("REDBALDKNIGHT", "Tick"),
        "Carbanak" to listOf("Anunak"),
        "Chimera" to emptyList(),
        "Cinnamon Tempest" to listOf("DEV-0401", "Emperor Dragonfly", "BRONZE STARLIGHT"),
        "Cleaver" to listOf("Threat Group 2889", "TG-2889"),
        "Cobalt Group" to listOf("GOLD KINGSWOOD", "Cobalt Gang", "Cobalt Spider"),
        "Confucius" to listOf("Confucius APT"),
        "Contagious Interview" to listOf("DeceptiveDevelopment", "Gwisin Gang", "Tenacious Pungsan", "DEV#POPPER", "PurpleBravo", "TAG-121"),
        "CopyKittens" to emptyList(),
        "CURIUM" to listOf("Crimson Sandstorm", "TA456", "Tortoise Shell", "Yellow Liderc"),
        "Daggerfly" to listOf("Evasive Panda", "BRONZE HIGHLAND"),
        "Dark Caracal" to emptyList(),
        "Darkhotel" to listOf("DUBNIUM", "Zigzag Hail"),
        "DarkHydrus" to emptyList(),
        "DarkVishnya" to emptyList(),
        "Deep Panda" to listOf("Shell Crew", "WebMasters", "KungFu Kittens", "PinkPanther", "Black Vine"),
        "Dragonfly" to listOf("TEMP.Isotope", "DYMALLOY", "Berserk Bear", "TG-4192", "Crouching Yeti", "IRON LIBERTY", "Energetic Bear", "Ghost Blizzard", "BROMINE"),
        "DragonOK" to emptyList(),
        "Earth Lusca" to listOf("TAG-22", "Charcoal Typhoon", "CHROMIUM", "ControlX"),
        "Elderwood" to listOf("Elderwood Gang", "Beijing Group", "Sneaky Panda"),
        "Ember Bear" to listOf("UNC2589", "Bleeding Bear", "DEV-0586", "Cadet Blizzard", "Frozenvista", "UAC-0056"),
        "Equation" to emptyList(),
        "Evilnum" to emptyList(),
        "EXOTIC LILY" to emptyList(),
        "Ferocious Kitten" to emptyList(),
        "FIN10" to emptyList(),
        "FIN13" to listOf("Elephant Beetle"),
        "FIN4" to emptyList(),
        "FIN5" to emptyList(),
        "FIN6" to listOf("Magecart Group 6", "ITG08", "Skeleton Spider", "TAAL", "Camouflage Tempest"),
        "FIN7" to listOf("GOLD NIAGARA", "ITG14", "Carbon Spider", "ELBRUS", "Sangria Tempest"),
        "FIN8" to listOf("Syssphinx"),
        "Fox Kitten" to listOf("UNC757", "Parisite", "Pioneer Kitten", "RUBIDIUM", "Lemon Sandstorm"),
        "GALLIUM" to listOf("Granite Typhoon"),
        "Gallmaker" to emptyList(),
        "Gamaredon Group" to listOf("IRON TILDEN", "Primitive Bear", "ACTINIUM", "Armageddon", "Shuckworm", "DEV-0157", "Aqua Blizzard"),
        "GCMAN" to emptyList(),
        "GOLD SOUTHFIELD" to listOf("Pinchy Spider"),
        "Gorgon Group" to emptyList(),
        "Group5" to emptyList(),
        "HAFNIUM" to listOf("Operation Exchange Marauder", "Silk Typhoon"),
        "HEXANE" to listOf("Lyceum", "Siamesekitten", "Spirlin"),
        "Higaisa" to emptyList(),
        "INC Ransom" to listOf("GOLD IONIC"),
        "Inception" to listOf("Inception Framework", "Cloud Atlas"),
        "IndigoZebra" to emptyList(),
        "Indrik Spider" to listOf("Evil Corp", "Manatee Tempest", "DEV-0243", "UNC2165"),
        "Ke3chang" to listOf("APT15", "Mirage", "Vixen Panda", "GREF", "Playful Dragon", "RoyalAPT", "NICKEL", "Nylon Typhoon"),
        "Kimsuky" to listOf("Black Banshee", "Velvet Chollima", "Emerald Sleet", "THALLIUM", "APT43", "TA427", "Springtail"),
        "LAPSUS$" to listOf("DEV-0537", "Strawberry Tempest"),
        "Lazarus Group" to listOf("Labyrinth Chollima", "HIDDEN COBRA", "Guardians of Peace", "ZINC", "NICKEL ACADEMY", "Diamond Sleet"),
        "LazyScripter" to emptyList(),
        "Leafminer" to listOf("Raspite"),
        "Leviathan" to listOf("MUDCARP", "Kryptonite Panda", "Gadolinium", "BRONZE MOHAWK", "TEMP.Jumper", "APT40", "TEMP.Periscope", "Gingham Typhoon"),
        "Lotus Blossom" to listOf("DRAGONFISH", "Spring Dragon", "RADIUM", "Raspberry Typhoon", "Bilbug", "Thrip"),
        "LuminousMoth" to emptyList(),
        "Machete" to listOf("APT-C-43", "El Machete"),
        "Magic Hound" to listOf("TA453", "COBALT ILLUSION", "Charming Kitten", "ITG18", "Phosphorus", "Newscaster", "APT35", "Mint Sandstorm"),
        "Malteiro" to emptyList(),
        "Medusa Group" to emptyList(),
        "menuPass" to listOf("Cicada", "POTASSIUM", "Stone Panda", "APT10", "Red Apollo", "CVNX", "HOGFISH", "BRONZE RIVERSIDE"),
        "Metador" to emptyList(),
        "Moafee" to emptyList(),
        "Mofang" to emptyList(),
        "Molerats" to listOf("Operation Molerats", "Gaza Cybergang"),
        "Moonstone Sleet" to listOf("Storm-1789"),
        "Moses Staff" to listOf("DEV-0500", "Marigold Sandstorm"),
        "MoustachedBouncer" to emptyList(),
        "MuddyWater" to listOf("Earth Vetala", "MERCURY", "Static Kitten", "Seedworm", "TEMP.Zagros", "Mango Sandstorm", "TA450"),
        "Mustang Panda" to listOf("TA416", "RedDelta", "BRONZE PRESIDENT", "STATELY TAURUS", "FIREANT", "CAMARO DRAGON", "EARTH PRETA", "HIVE0154", "TWILL TYPHOON", "TANTALUM", "LUMINOUS MOTH", "UNC6384", "TEMP.Hex", "Red Lich"),
        "Mustard Tempest" to listOf("DEV-0206", "TA569", "GOLD PRELUDE", "UNC1543"),
        "Naikon" to emptyList(),
        "NEODYMIUM" to emptyList(),
        "Nomadic Octopus" to listOf("DustSquad"),
        "OilRig" to listOf("COBALT GYPSY", "IRN2", "APT34", "Helix Kitten", "Evasive Serpens", "Hazel Sandstorm", "EUROPIUM", "ITG13", "Earth Simnavaz", "Crambus", "TA452"),
        "Orangeworm" to emptyList(),
        "Patchwork" to listOf("Hangover Group", "Dropping Elephant", "Chinastrats", "MONSOON", "Operation Hangover"),
        "PittyTiger" to emptyList(),
        "PLATINUM" to emptyList(),
        "Play" to emptyList(),
        "POLONIUM" to listOf("Plaid Rain"),
        "Poseidon Group" to emptyList(),
        "PROMETHIUM" to listOf("StrongPity"),
        "Putter Panda" to listOf("APT2", "MSUpdater"),
        "Rancor" to emptyList(),
        "RedCurl" to emptyList(),
        "RedEcho" to emptyList(),
        "Rocke" to emptyList(),
        "RTM" to emptyList(),
        "Saint Bear" to listOf("Storm-0587", "TA471", "UAC-0056", "Lorec53"),
        "Salt Typhoon" to emptyList(),
        "Sandworm Team" to listOf("ELECTRUM", "Telebots", "IRON VIKING", "BlackEnergy (Group)", "Quedagh", "Voodoo Bear", "IRIDIUM", "Seashell Blizzard", "FROZENBARENTS", "APT44"),
        "Scarlet Mimic" to emptyList(),
        "Scattered Spider" to listOf("Roasted 0ktapus", "Octo Tempest", "Storm-0875", "UNC3944"),
        "Sea Turtle" to listOf("Teal Kurma", "Marbled Dust", "Cosmic Wolf", "SILICON"),
        "SideCopy" to emptyList(),
        "Sidewinder" to listOf("T-APT-04", "Rattlesnake"),
        "Silence" to listOf("Whisper Spider"),
        "Silent Librarian" to listOf("TA407", "COBALT DICKENS"),
        "SilverTerrier" to emptyList(),
        "Sowbug" to emptyList(),
        "Star Blizzard" to listOf("SEABORGIUM", "Callisto Group", "TA446", "COLDRIVER"),
        "Stealth Falcon" to emptyList(),
        "Storm-0501" to emptyList(),
        "Storm-1811" to emptyList(),
        "Strider" to listOf("ProjectSauron"),
        "Suckfly" to emptyList(),
        "TA2541" to emptyList(),
        "TA459" to emptyList(),
        "TA505" to listOf("Hive0065", "Spandex Tempest", "CHIMBORAZO"),
        "TA551" to listOf("GOLD CABIN", "Shathak"),
        "TA577" to emptyList(),
        "TA578" to emptyList(),
        "TeamTNT" to emptyList(),
        "TEMP.Veles" to listOf("XENOTIME"),
        "The White Company" to emptyList(),
        "Threat Group-1314" to listOf("TG-1314"),
        "Threat Group-3390" to listOf("Earth Smilodon", "TG-3390", "Emissary Panda", "BRONZE UNION", "APT27", "Iron Tiger", "LuckyMouse", "Linen Typhoon"),
        "Thrip" to emptyList(),
        "ToddyCat" to emptyList(),
        "Tonto Team" to listOf("Earth Akhlut", "BRONZE HUNTLEY", "CactusPete", "Karma Panda"),
        "Transparent Tribe" to listOf("COPPER FIELDSTONE", "APT36", "Mythic Leopard", "ProjectM"),
        "Tropic Trooper" to listOf("Pirate Panda", "KeyBoy"),
        "Turla" to listOf("IRON HUNTER", "Group 88", "Waterbug", "WhiteBear", "Snake", "Krypton", "Venomous Bear", "Secret Blizzard", "BELUGASTURGEON"),
        "UNC3886" to emptyList(),
        "Velvet Ant" to emptyList(),
        "Volatile Cedar" to listOf("Lebanese Cedar"),
        "Volt Typhoon" to listOf("BRONZE SILHOUETTE", "Vanguard Panda", "DEV-0391", "UNC3236", "Voltzite", "Insidious Taurus"),
        "Water Galura" to listOf("GOLD FEATHER"),
        "Whitefly" to emptyList(),
        "Windigo" to emptyList(),
        "Windshift" to listOf("Bahamut"),
        "Winnti Group" to listOf("Blackfly"),
        "Winter Vivern" to listOf("TA473", "UAC-0114"),
        "WIRTE" to emptyList(),
        "Wizard Spider" to listOf("UNC1878", "TEMP.MixMaster", "Grim Spider", "FIN12", "GOLD BLACKBURN", "ITG23", "Periwinkle Tempest", "DEV-0193"),
        "ZIRCONIUM" to listOf("APT31", "Violet Typhoon"),
    )

    private val softwareData = listOf(
        "3PARA RAT" to emptyList(), "4H RAT" to emptyList(), "AADInternals" to emptyList(),
        "ABK" to emptyList(), "AcidPour" to emptyList(), "AcidRain" to emptyList(),
        "Action RAT" to emptyList(), "adbupd" to emptyList(), "AdFind" to emptyList(),
        "ADVSTORESHELL" to listOf("AZZY", "EVILTOSS", "NETUI", "Sedreco"),
        "Agent Tesla" to emptyList(), "Agent.btz" to emptyList(),
        "Akira" to emptyList(), "Akira _v2" to emptyList(), "Amadey" to emptyList(),
        "Anchor" to listOf("Anchor_DNS"), "ANDROMEDA" to emptyList(),
        "Apostle" to emptyList(), "AppleJeus" to emptyList(), "AppleSeed" to emptyList(),
        "Aria-body" to emptyList(), "ASPXSpy" to listOf("ASPXTool"),
        "Astaroth" to listOf("Guildma"), "AsyncRAT" to emptyList(),
        "Attor" to emptyList(), "AuditCred" to listOf("Roptimizer"),
        "AuTo Stealer" to emptyList(), "AutoIt backdoor" to emptyList(),
        "Avaddon" to emptyList(), "Avenger" to emptyList(), "AvosLocker" to emptyList(),
        "Azorult" to emptyList(), "Babuk" to listOf("Babyk", "Vasa Locker"),
        "BabyShark" to listOf("LATEOP"), "BackConfig" to emptyList(),
        "Backdoor.Oldrea" to listOf("Havex"), "BACKSPACE" to listOf("Lecna"),
        "Bad Rabbit" to listOf("Win32/Diskcoder.D"), "BADCALL" to emptyList(),
        "BADFLICK" to emptyList(), "BADHATCH" to emptyList(), "BADNEWS" to emptyList(),
        "BadPatch" to emptyList(), "Bandook" to emptyList(),
        "Bankshot" to listOf("Trojan Manuscript"), "Bazar" to listOf("KEGTAP", "Team9", "Bazaloader"),
        "BBK" to emptyList(), "BBSRAT" to emptyList(), "BeaverTail" to emptyList(),
        "BendyBear" to emptyList(), "BFG Agonizer" to emptyList(), "BISCUIT" to emptyList(),
        "Bisonal" to emptyList(), "BitPaymer" to listOf("wp_encrypt", "FriedEx"),
        "BITSAdmin" to emptyList(), "Black Basta" to emptyList(),
        "BlackByte 2.0 Ransomware" to emptyList(), "BlackByte Ransomware" to emptyList(),
        "BlackCat" to listOf("ALPHV", "Noberus"), "BLACKCOFFEE" to emptyList(),
        "BlackEnergy" to listOf("Black Energy"), "BlackMould" to emptyList(),
        "BLINDINGCAN" to emptyList(), "BloodHound" to emptyList(), "BLUELIGHT" to emptyList(),
        "BOLDMOVE" to emptyList(), "Bonadan" to emptyList(), "BONDUPDATER" to emptyList(),
        "BOOKWORM" to emptyList(), "BoomBox" to emptyList(), "BOOSTWRITE" to emptyList(),
        "BOOTRASH" to emptyList(), "BoxCaon" to emptyList(),
        "BPFDoor" to listOf("JustForFun", "Backdoor.Linux.BPFDOOR", "Backdoor.Solaris.BPFDOOR.ZAJE"),
        "Brave Prince" to emptyList(), "Briba" to emptyList(),
        "Brute Ratel C4" to listOf("BRc4"), "BS2005" to emptyList(),
        "BUBBLEWRAP" to listOf("Backdoor.APT.FakeWinHTTPHelper"),
        "build_downer" to emptyList(), "Bumblebee" to emptyList(),
        "Bundlore" to listOf("OSX.Bundlore"), "BUSHWALK" to emptyList(),
        "Cachedump" to emptyList(), "CaddyWiper" to emptyList(), "Cadelspy" to emptyList(),
        "CALENDAR" to emptyList(), "Calisto" to emptyList(), "CallMe" to emptyList(),
        "Cannon" to emptyList(), "CANONSTAGER" to emptyList(),
        "Carbanak" to listOf("Anunak"), "Carberp" to emptyList(), "Carbon" to emptyList(),
        "Cardinal RAT" to emptyList(), "CARROTBALL" to emptyList(), "CARROTBAT" to emptyList(),
        "CASTLETAP" to emptyList(), "Catchamas" to emptyList(),
        "Caterpillar WebShell" to emptyList(), "CCBkdr" to emptyList(), "ccf32" to emptyList(),
        "cd00r" to emptyList(), "Chaes" to emptyList(), "Chaos" to emptyList(),
        "CharmPower" to emptyList(), "ChChes" to listOf("Scorpion", "HAYMAKER"),
        "Cheerscrypt" to emptyList(), "Cherry Picker" to emptyList(),
        "CHIMNEYSWEEP" to emptyList(), "China Chopper" to emptyList(), "Chinoxy" to emptyList(),
        "CHOPSTICK" to listOf("Backdoor.SofacyX", "SPLM", "Xagent", "X-Agent", "webhp"),
        "Chrommme" to emptyList(), "CLAIMLOADER" to emptyList(), "Clambling" to emptyList(),
        "Clop" to emptyList(), "CloudDuke" to listOf("MiniDionis", "CloudLook"),
        "COATHANGER" to emptyList(), "Cobalt Strike" to emptyList(),
        "Cobian RAT" to emptyList(), "CoinTicker" to emptyList(), "Comnie" to emptyList(),
        "ComRAT" to emptyList(), "Conficker" to listOf("Kido", "Downadup"),
        "ConnectWise" to listOf("ScreenConnect"), "Conti" to emptyList(),
        "CookieMiner" to emptyList(), "CORALDECK" to emptyList(),
        "CORESHELL" to listOf("Sofacy", "SOURFACE"), "CorKLOG" to emptyList(),
        "CosmicDuke" to listOf("TinyBaron", "BotgenStudios", "NemesisGemina"),
        "CostaBricks" to emptyList(), "Covenant" to emptyList(),
        "CozyCar" to listOf("CozyDuke", "CozyBear", "Cozer", "EuroAPT"),
        "CrackMapExec" to emptyList(), "CreepyDrive" to emptyList(), "CreepySnail" to emptyList(),
        "Crimson" to listOf("MSIL/Crimson"), "CrossRAT" to emptyList(), "Crutch" to emptyList(),
        "Cryptoistic" to emptyList(), "CSPY Downloader" to emptyList(), "Cuba" to emptyList(),
        "Cuckoo Stealer" to emptyList(), "Cyclops Blink" to emptyList(), "Dacls" to emptyList(),
        "DanBot" to emptyList(), "DarkComet" to listOf("DarkKomet", "Fynloski", "Krademok", "FYNLOS"),
        "DarkGate" to emptyList(), "DarkTortilla" to emptyList(), "DarkWatchman" to emptyList(),
        "Daserf" to listOf("Muirim", "Nioupale"), "DCSrv" to emptyList(), "DDKONG" to emptyList(),
        "DEADEYE" to listOf("DEADEYE.EMBED", "DEADEYE.APPEND"), "DEADWOOD" to emptyList(),
        "DealersChoice" to emptyList(), "DEATHRANSOM" to emptyList(), "Denis" to emptyList(),
        "Derusbi" to listOf("PHOTO"), "Diavol" to emptyList(), "Dipsind" to emptyList(),
        "Disco" to emptyList(), "DnsSystem" to emptyList(), "DOGCALL" to emptyList(),
        "Dok" to listOf("Retefe"), "Doki" to emptyList(), "Donut" to emptyList(),
        "down_new" to emptyList(), "Downdelph" to listOf("Delphacy"), "DownPaper" to emptyList(),
        "DRATzarus" to emptyList(), "Dridex" to listOf("Bugat v5"), "DropBook" to emptyList(),
        "Drovorub" to emptyList(), "Dtrack" to emptyList(), "Duqu" to emptyList(),
        "DUSTPAN" to emptyList(), "DUSTTRAP" to emptyList(),
        "DustySky" to listOf("NeD Worm"), "Dyre" to listOf("Dyzap", "Dyreza"),
        "Ebury" to emptyList(), "ECCENTRICBANDWAGON" to emptyList(),
        "Ecipekac" to listOf("HEAVYHAND", "SigLoader", "DESLoader"), "Egregor" to emptyList(),
        "EKANS" to listOf("SNAKEHOSE"), "Elise" to listOf("BKDR_ESILE", "Page"),
        "ELMER" to emptyList(), "Embargo" to emptyList(), "Emissary" to emptyList(),
        "Emotet" to listOf("Geodo"), "Empire" to listOf("EmPyre", "PowerShell Empire"),
        "EnvyScout" to emptyList(),
        "Epic" to listOf("Tavdig", "Wipbot", "WorldCupSec", "TadjMakhal"),
        "EvilBunny" to emptyList(), "EvilGrab" to emptyList(), "EVILNUM" to emptyList(),
        "Exaramel for Linux" to emptyList(), "Exaramel for Windows" to emptyList(),
        "Exbyte" to emptyList(), "Explosive" to emptyList(), "FakeM" to emptyList(),
        "FALLCHILL" to emptyList(), "FatDuke" to emptyList(), "Felismus" to emptyList(),
        "FELIXROOT" to listOf("GreyEnergy mini"), "Ferocious" to emptyList(),
        "Fgdump" to emptyList(), "Final1stspy" to emptyList(),
        "FinFisher" to listOf("FinSpy"), "FIVEHANDS" to emptyList(), "Flagpro" to emptyList(),
        "Flame" to listOf("Flamer", "sKyWIper"), "FLASHFLOOD" to emptyList(),
        "FlawedAmmyy" to emptyList(), "FlawedGrace" to emptyList(), "FLIPSIDE" to emptyList(),
        "FoggyWeb" to emptyList(), "FRAMESTING" to emptyList(),
        "FrameworkPOS" to listOf("Trinity"), "FRP" to emptyList(), "FruitFly" to emptyList(),
        "FunnyDream" to emptyList(), "FYAnti" to listOf("DILLJUICE stage2"),
        "Fysbis" to emptyList(), "Gazer" to listOf("WhiteBear"),
        "Gelsemium" to listOf("Gelsevirine", "Gelsenicine", "Gelsemine"),
        "GeminiDuke" to emptyList(), "Get2" to emptyList(),
        "gh0st RAT" to listOf("Mydoor", "Moudoor"), "GLASSTOKEN" to emptyList(),
        "GLOOXMAIL" to listOf("Trojan.GTALK"), "GoBear" to emptyList(),
        "Gold Dragon" to emptyList(), "GoldenSpy" to emptyList(), "GoldFinder" to emptyList(),
        "GoldMax" to listOf("SUNSHUTTLE"), "Gomir" to emptyList(), "Goopy" to emptyList(),
        "Gootloader" to emptyList(), "Grandoreiro" to emptyList(), "GravityRAT" to emptyList(),
        "Green Lambert" to emptyList(), "GreyEnergy" to emptyList(), "GRIFFON" to emptyList(),
        "GrimAgent" to emptyList(), "gsecdump" to emptyList(), "GuLoader" to emptyList(),
        "H1N1" to emptyList(), "Hacking Team UEFI Rootkit" to emptyList(),
        "HALFBAKED" to emptyList(), "HAMMERTOSS" to listOf("HammerDuke", "NetDuke"),
        "Hancitor" to listOf("Chanitor"), "Hannotog" to emptyList(), "HAPPYWORK" to emptyList(),
        "HARDRAIN" to emptyList(), "Havij" to emptyList(), "Havoc" to emptyList(),
        "HAWKBALL" to emptyList(), "hcdLoader" to emptyList(),
        "HDoor" to listOf("Custom HDoor"), "HELLOKITTY" to emptyList(),
        "Helminth" to emptyList(), "HermeticWiper" to listOf("Trojan.Killdisk", "DriveSlayer"),
        "HermeticWizard" to emptyList(), "HexEval Loader" to emptyList(),
        "Heyoka Backdoor" to emptyList(), "Hi-Zor" to emptyList(), "HiddenWasp" to emptyList(),
        "HIDEDRV" to emptyList(), "Hikit" to emptyList(), "Hildegard" to emptyList(),
        "HIUPAN" to emptyList(), "HOMEFRY" to emptyList(), "HOPLIGHT" to emptyList(),
        "HotCroissant" to emptyList(), "HTRAN" to listOf("HUC Packet Transmit Tool"),
        "HTTPBrowser" to listOf("Token Control", "HttpDump"), "httpclient" to emptyList(),
        "HUI Loader" to emptyList(),
        "Hydraq" to listOf("Roarur", "MdmBot", "HomeUnix", "Homux", "HidraQ", "HydraQ", "McRat", "Aurora", "9002 RAT"),
        "HyperBro" to emptyList(), "HyperStack" to emptyList(), "IceApple" to emptyList(),
        "IcedID" to emptyList(), "iKitten" to listOf("OSX/MacDownloader"),
        "IMAPLoader" to emptyList(), "Imminent Monitor" to emptyList(), "Impacket" to emptyList(),
        "INC Ransomware" to emptyList(),
        "Industroyer" to listOf("CRASHOVERRIDE", "Win32/Industroyer"),
        "Industroyer2" to emptyList(), "InnaputRAT" to emptyList(),
        "InvisibleFerret" to emptyList(), "InvisiMole" to emptyList(),
        "Invoke-PSImage" to emptyList(), "IPsec Helper" to emptyList(),
        "IronNetInjector" to emptyList(), "ISMInjector" to emptyList(), "Ixeshe" to emptyList(),
        "J-magic" to emptyList(), "Janicab" to emptyList(), "Javali" to emptyList(),
        "JCry" to emptyList(),
        "JHUHUGIT" to listOf("Trojan.Sofacy", "Seduploader", "JKEYSKW", "Sednit", "GAMEFISH", "SofacyCarberp"),
        "JPIN" to emptyList(),
        "jRAT" to listOf("JSocket", "AlienSpy", "Frutas", "Sockrat", "Unrecom", "jFrutas", "Adwind", "jBiFrost", "Trojan.Maljava"),
        "JSS Loader" to emptyList(), "JumbledPath" to emptyList(),
        "Kapeka" to listOf("KnuckleTouch"), "KARAE" to emptyList(), "Kasidet" to emptyList(),
        "Kazuar" to emptyList(), "Kerrdown" to emptyList(), "Kessel" to emptyList(),
        "Kevin" to emptyList(), "KeyBoy" to emptyList(),
        "Keydnap" to listOf("OSX/Keydnap"), "KEYMARBLE" to emptyList(),
        "KEYPLUG" to listOf("KEYPLUG.LINUX"), "KGH_SPY" to emptyList(),
        "KillDisk" to listOf("Win32/KillDisk.NBI", "Win32/KillDisk.NBH", "Win32/KillDisk.NBD", "Win32/KillDisk.NBC", "Win32/KillDisk.NBB"),
        "Kinsing" to emptyList(), "Kivars" to emptyList(), "Koadic" to emptyList(),
        "Kobalos" to emptyList(), "KOCTOPUS" to emptyList(), "Komplex" to emptyList(),
        "KOMPROGO" to emptyList(), "KONNI" to emptyList(), "KOPILUWAK" to emptyList(),
        "Kwampirs" to emptyList(), "Latrodectus" to listOf("IceNova", "Unidentified 111"),
        "LaZagne" to emptyList(), "LightNeuron" to emptyList(), "LightSpy" to emptyList(),
        "LIGHTWIRE" to emptyList(), "Line Dancer" to emptyList(), "Line Runner" to emptyList(),
        "Linfo" to emptyList(), "Linux Rabbit" to emptyList(), "LiteDuke" to emptyList(),
        "LitePower" to emptyList(), "LITTLELAMB.WOOLTEA" to emptyList(),
        "Lizar" to listOf("Tirion", "Icebot", "DiceLoader"),
        "LockBit 2.0" to emptyList(), "LockBit 3.0" to listOf("LockBit Black"),
        "LockerGoga" to emptyList(), "LoFiSe" to emptyList(), "LoJax" to emptyList(),
        "Lokibot" to emptyList(), "LookBack" to emptyList(), "LoudMiner" to emptyList(),
        "LOWBALL" to emptyList(), "Lslsass" to emptyList(), "Lucifer" to emptyList(),
        "Lumma Stealer" to listOf("LummaStealer"), "LunarLoader" to emptyList(),
        "LunarMail" to emptyList(), "LunarWeb" to emptyList(), "Lurid" to listOf("Enfal"),
        "Machete" to listOf("Pyark"), "MacMa" to listOf("OSX.CDDS", "DazzleSpy"),
        "macOS.OSAMiner" to emptyList(), "MacSpy" to emptyList(), "Mafalda" to emptyList(),
        "MagicRAT" to emptyList(), "MailSniper" to emptyList(), "Mango" to emptyList(),
        "Manjusaka" to emptyList(), "MarkiRAT" to emptyList(), "Matryoshka" to emptyList(),
        "Maze" to emptyList(), "MCMD" to emptyList(), "MechaFlounder" to emptyList(),
        "MEDUSA" to emptyList(), "Medusa Ransomware" to emptyList(), "meek" to emptyList(),
        "MegaCortex" to emptyList(), "Megazord" to emptyList(), "Melcoz" to emptyList(),
        "MESSAGETAP" to emptyList(), "metaMain" to emptyList(),
        "Metamorfo" to listOf("Casbaneiro"), "Meteor" to emptyList(), "MgBot" to emptyList(),
        "Micropsia" to emptyList(), "Milan" to listOf("James"), "Mimikatz" to emptyList(),
        "MimiPenguin" to emptyList(), "Miner-C" to emptyList(), "MiniDuke" to emptyList(),
        "MirageFox" to emptyList(), "Mis-Type" to emptyList(), "Misdat" to emptyList(),
        "Mispadu" to emptyList(), "Mivast" to emptyList(), "MobileOrder" to emptyList(),
        "MoleNet" to emptyList(), "Moneybird" to emptyList(), "Mongall" to emptyList(),
        "MoonWind" to emptyList(), "MOPSLED" to emptyList(),
        "More_eggs" to listOf("SKID", "Terra Loader", "SpicyOmelette"),
        "Mori" to emptyList(), "Mosquito" to emptyList(), "MultiLayer Wiper" to emptyList(),
        "MURKYTOP" to emptyList(), "Mythic" to emptyList(), "Naid" to emptyList(),
        "NanHaiShu" to emptyList(), "NanoCore" to emptyList(), "NativeZone" to emptyList(),
        "NavRAT" to emptyList(), "NBTscan" to emptyList(), "NDiskMonitor" to emptyList(),
        "Nebulae" to emptyList(), "Neo-reGeorg" to emptyList(), "Neoichor" to emptyList(),
        "Nerex" to emptyList(), "Net Crawler" to listOf("NetC"), "NETEAGLE" to emptyList(),
        "NetTraveler" to emptyList(), "Netwalker" to emptyList(), "NETWIRE" to emptyList(),
        "NGLite" to emptyList(), "ngrok" to emptyList(), "NICECURL" to emptyList(),
        "Nidiran" to listOf("Backdoor.Nidiran"), "NightClub" to emptyList(),
        "Nightdoor" to emptyList(), "Ninja" to emptyList(),
        "njRAT" to listOf("Njw0rm", "LV", "Bladabindi"), "NKAbuse" to emptyList(),
        "NOKKI" to emptyList(),
        "NotPetya" to listOf("ExPetr", "Diskcoder.C", "GoldenEye", "Petrwrap", "Nyetya"),
        "NPPSPY" to emptyList(), "ObliqueRAT" to emptyList(), "OceanSalt" to emptyList(),
        "Octopus" to emptyList(), "ODAgent" to emptyList(), "OilBooster" to emptyList(),
        "OilCheck" to emptyList(), "Okrum" to emptyList(),
        "OLDBAIT" to listOf("Sasfis"), "Olympic Destroyer" to emptyList(),
        "OnionDuke" to emptyList(), "OopsIE" to emptyList(), "Orz" to listOf("AIRBREAK"),
        "OSInfo" to emptyList(), "OSX/Shlayer" to listOf("Zshlayer", "Crossrider"),
        "OSX_OCEANLOTUS.D" to listOf("Backdoor.MacOS.OCEANLOTUS.F"),
        "Out1" to emptyList(), "OutSteel" to emptyList(), "OwaAuth" to emptyList(),
        "P.A.S. Webshell" to listOf("Fobushell"),
        "P2P ZeuS" to listOf("Peer-to-Peer ZeuS", "Gameover ZeuS"),
        "P8RAT" to listOf("HEAVYPOT", "GreetCake"), "PACEMAKER" to emptyList(),
        "Pacu" to emptyList(), "PAKLOG" to emptyList(), "Pandora" to emptyList(),
        "Pasam" to emptyList(), "Pass-The-Hash Toolkit" to emptyList(),
        "Pay2Key" to emptyList(), "Pcexter" to emptyList(), "PcShare" to emptyList(),
        "Peirates" to emptyList(), "Penquin" to listOf("Penquin 2.0", "Penquin_x64"),
        "Peppy" to emptyList(), "PHOREAL" to emptyList(), "Pikabot" to emptyList(),
        "Pillowmint" to emptyList(), "PinchDuke" to emptyList(), "PingPull" to emptyList(),
        "PipeMon" to emptyList(), "Pisloader" to emptyList(), "PITSTOP" to emptyList(),
        "PLAINTEE" to emptyList(), "Playcrypt" to listOf("Play"), "PLEAD" to emptyList(),
        "PlugX" to listOf("Thoper", "TVT", "DestroyRAT", "Sogu", "Kaba", "Korplug"),
        "pngdowner" to emptyList(), "PoetRAT" to emptyList(),
        "PoisonIvy" to listOf("Breut", "Poison Ivy", "Darkmoon"),
        "PolyglotDuke" to emptyList(), "Pony" to emptyList(), "POORAIM" to emptyList(),
        "PoshC2" to emptyList(), "POSHSPY" to emptyList(), "Power Loader" to emptyList(),
        "PowerDuke" to emptyList(), "PowerExchange" to emptyList(), "PowerLess" to emptyList(),
        "PowerPunch" to emptyList(), "PowerShower" to emptyList(),
        "POWERSOURCE" to listOf("DNSMessenger"), "PowerSploit" to emptyList(),
        "PowerStallion" to emptyList(), "POWERSTATS" to listOf("Powermud"),
        "POWERTON" to emptyList(), "PowGoop" to emptyList(), "POWRUNER" to emptyList(),
        "Prestige" to emptyList(), "Prikormka" to emptyList(), "ProLock" to emptyList(),
        "Proton" to emptyList(), "Proxysvc" to emptyList(), "PS1" to emptyList(),
        "PsExec" to emptyList(), "Psylo" to emptyList(),
        "Pteranodon" to listOf("Pterodo"), "PUBLOAD" to emptyList(),
        "PULSECHECK" to emptyList(), "PUNCHBUGGY" to listOf("ShellTea"),
        "PUNCHTRACK" to listOf("PSVC"), "Pupy" to emptyList(), "pwdump" to emptyList(),
        "PyDCrypt" to emptyList(), "Pysa" to listOf("Mespinoza"),
        "QakBot" to listOf("Pinkslipbot", "QuackBot", "QBot"),
        "Qilin" to listOf("Agenda"), "QUADAGENT" to emptyList(),
        "QuasarRAT" to listOf("xRAT"), "Quick Assist" to emptyList(),
        "QUIETCANARY" to listOf("Tunnus"), "QUIETEXIT" to emptyList(),
        "QuietSieve" to emptyList(), "Raccoon Stealer" to emptyList(),
        "Ragnar Locker" to emptyList(), "Raindrop" to emptyList(), "RainyDay" to emptyList(),
        "Ramsay" to emptyList(), "RansomHub" to emptyList(), "RAPIDPULSE" to emptyList(),
        "RARSTONE" to emptyList(), "Raspberry Robin" to emptyList(), "RATANKBA" to emptyList(),
        "RawDisk" to emptyList(), "RawPOS" to listOf("FIENDCRY", "DUEBREW", "DRIFTWOOD"),
        "Rclone" to emptyList(), "RCSession" to emptyList(), "RDAT" to emptyList(),
        "RDFSNIFFER" to emptyList(), "Reaver" to emptyList(),
        "RedLeaves" to listOf("BUGJUICE"), "RedLine Stealer" to emptyList(),
        "RegDuke" to emptyList(), "reGeorg" to emptyList(), "Regin" to emptyList(),
        "Remcos" to emptyList(), "Remexi" to emptyList(), "RemoteCMD" to emptyList(),
        "RemoteUtilities" to emptyList(),
        "Remsec" to listOf("Backdoor.Remsec", "ProjectSauron"),
        "REPTILE" to emptyList(), "Responder" to emptyList(), "Revenge RAT" to emptyList(),
        "REvil" to listOf("Sodin", "Sodinokibi"), "RGDoor" to emptyList(),
        "Rifdoor" to emptyList(), "RIFLESPINE" to emptyList(), "RIPTIDE" to emptyList(),
        "Rising Sun" to emptyList(), "ROADSWEEP" to emptyList(), "ROADTools" to emptyList(),
        "RobbinHood" to emptyList(), "ROCKBOOT" to emptyList(), "RogueRobin" to emptyList(),
        "ROKRAT" to emptyList(), "RotaJakiro" to emptyList(), "Rover" to emptyList(),
        "Royal" to emptyList(), "RTM" to listOf("Redaman"), "Rubeus" to emptyList(),
        "Ruler" to emptyList(), "RunningRAT" to emptyList(), "Ryuk" to emptyList(),
        "S-Type" to emptyList(), "Sagerunex" to emptyList(), "Saint Bot" to emptyList(),
        "Sakula" to listOf("Sakurel", "VIPER"),
        "SampleCheck5000" to listOf("SC5k"), "SamSam" to listOf("Samas"),
        "Samurai" to emptyList(), "Sardonic" to emptyList(), "SDBbot" to emptyList(),
        "SDelete" to emptyList(), "SeaDuke" to listOf("SeaDaddy", "SeaDesk"),
        "Seasalt" to emptyList(), "SEASHARPEE" to emptyList(), "ServHelper" to emptyList(),
        "Seth-Locker" to emptyList(), "ShadowPad" to listOf("POISONPLUG.SHADOW"),
        "Shamoon" to listOf("Disttrack"), "Shark" to emptyList(), "SharpDisco" to emptyList(),
        "SharpStage" to emptyList(), "SHARPSTATS" to emptyList(), "ShimRat" to emptyList(),
        "ShimRatReporter" to emptyList(), "SHIPSHAPE" to emptyList(),
        "SHOTPUT" to listOf("Backdoor.APT.CookieCutter", "Pirpi"),
        "ShrinkLocker" to emptyList(), "SHUTTERSPEED" to emptyList(), "Sibot" to emptyList(),
        "SideTwist" to emptyList(), "SILENTTRINITY" to emptyList(), "Siloscape" to emptyList(),
        "Skeleton Key" to emptyList(), "Skidmap" to emptyList(), "SLIGHTPULSE" to emptyList(),
        "Sliver" to emptyList(), "SLOTHFULMEDIA" to listOf("JackOfHearts", "QueenOfClubs"),
        "SLOWDRIFT" to emptyList(), "SLOWPULSE" to emptyList(),
        "Small Sieve" to listOf("GRAMDOOR"),
        "Smoke Loader" to listOf("Dofoil"), "SMOKEDHAM" to emptyList(),
        "SnappyTCP" to emptyList(), "Snip3" to emptyList(), "SNUGRIDE" to emptyList(),
        "SocGholish" to listOf("FakeUpdates"), "Socksbot" to emptyList(),
        "SodaMaster" to listOf("DARKTOWN", "dfls", "DelfsCake"),
        "Solar" to emptyList(), "SombRAT" to emptyList(), "SoreFang" to emptyList(),
        "SOUNDBITE" to emptyList(), "SPACESHIP" to emptyList(), "Spark" to emptyList(),
        "SpeakUp" to emptyList(), "Spica" to emptyList(), "SpicyOmelette" to emptyList(),
        "SplatCloak" to emptyList(), "SplatDropper" to emptyList(),
        "spwebmember" to emptyList(), "sqlmap" to emptyList(), "SQLRat" to emptyList(),
        "Squirrelwaffle" to emptyList(), "SslMM" to emptyList(), "Starloader" to emptyList(),
        "StarProxy" to emptyList(), "STARWHALE" to listOf("CANOPY"),
        "STATICPLUGIN" to emptyList(), "STEADYPULSE" to emptyList(), "StealBit" to emptyList(),
        "StoneDrill" to listOf("DROPSHOT"), "StreamEx" to emptyList(),
        "StrelaStealer" to emptyList(), "StrifeWater" to emptyList(),
        "StrongPity" to emptyList(), "Stuxnet" to listOf("W32.Stuxnet"),
        "SUGARDUMP" to emptyList(), "SUGARUSH" to emptyList(),
        "SUNBURST" to listOf("Solorigate"), "SUNSPOT" to emptyList(),
        "SUPERNOVA" to emptyList(), "SVCReady" to emptyList(), "Sykipot" to emptyList(),
        "SynAck" to emptyList(), "SYNful Knock" to emptyList(), "Sys10" to emptyList(),
        "SYSCON" to emptyList(),
        "SysUpdate" to listOf("HyperSSL", "Soldier", "FOCUSFJORD"),
        "T9000" to emptyList(), "Taidoor" to emptyList(), "TAINTEDSCRIBE" to emptyList(),
        "TajMahal" to emptyList(), "TAMECAT" to emptyList(), "Tarrask" to emptyList(),
        "TDTESS" to emptyList(), "TEARDROP" to emptyList(),
        "TEXTMATE" to listOf("DNSMessenger"),
        "ThiefQuest" to listOf("MacRansom.K", "EvilQuest"),
        "THINCRUST" to emptyList(), "ThreatNeedle" to emptyList(), "TinyTurla" to emptyList(),
        "TINYTYPHON" to emptyList(), "TinyZBot" to emptyList(), "Tomiris" to emptyList(),
        "TONESHELL" to emptyList(), "Tor" to emptyList(), "Torisma" to emptyList(),
        "TrailBlazer" to emptyList(), "TRANSLATEXT" to emptyList(),
        "TrickBot" to listOf("Totbrick", "TSPY_TRICKLOAD"),
        "Trojan.Karagany" to listOf("xFrost", "Karagany"),
        "Trojan.Mebromi" to emptyList(), "Troll Stealer" to emptyList(),
        "Truvasys" to emptyList(), "TSCookie" to emptyList(), "Turian" to emptyList(),
        "TURNEDUP" to emptyList(), "TYPEFRAME" to emptyList(), "UACMe" to emptyList(),
        "UBoatRAT" to emptyList(), "Umbreon" to emptyList(), "Unknown Logger" to emptyList(),
        "UPPERCUT" to listOf("ANEL"), "UPSTYLE" to emptyList(),
        "Uroburos" to listOf("Snake"),
        "Ursnif" to listOf("Gozi-ISFB", "PE_URSNIF", "Dreambot"),
        "USBferry" to emptyList(), "USBStealer" to listOf("USB Stealer", "Win32/USBStealer"),
        "Valak" to emptyList(), "VaporRage" to emptyList(), "Vasport" to emptyList(),
        "VBShower" to emptyList(), "VERMIN" to emptyList(), "VersaMem" to emptyList(),
        "VIRTUALPIE" to emptyList(), "VIRTUALPITA" to emptyList(), "Volgmer" to emptyList(),
        "VPNFilter" to emptyList(),
        "WannaCry" to listOf("WanaCry", "WanaCrypt", "WanaCrypt0r", "WCry"),
        "WARPWIRE" to emptyList(), "WarzoneRAT" to listOf("Warzone", "Ave Maria"),
        "WastedLocker" to emptyList(), "Waterbear" to emptyList(), "WEBC2" to emptyList(),
        "WellMail" to emptyList(), "WellMess" to emptyList(), "WhisperGate" to emptyList(),
        "Wiarp" to emptyList(), "Windows Credential Editor" to listOf("WCE"),
        "WINDSHIELD" to emptyList(), "WindTail" to emptyList(), "WINERACK" to emptyList(),
        "Winexe" to emptyList(), "Wingbird" to emptyList(), "WinMM" to emptyList(),
        "Winnti for Linux" to emptyList(), "Winnti for Windows" to emptyList(),
        "Wiper" to emptyList(), "WIREFIRE" to listOf("GIFTEDVISITOR"),
        "Woody RAT" to emptyList(), "XAgentOSX" to listOf("OSX.Sofacy"),
        "Xbash" to emptyList(), "xCaon" to emptyList(), "xCmd" to emptyList(),
        "XCSSET" to listOf("OSX.DubRobber"), "XLoader" to listOf("Formbook"),
        "XORIndex Loader" to emptyList(),
        "XTunnel" to listOf("Trojan.Shunnael", "X-Tunnel", "XAPS"),
        "YAHOYAH" to emptyList(), "yty" to emptyList(),
        "Zebrocy" to listOf("Zekapab"), "Zeroaccess" to emptyList(),
        "ZeroCleare" to listOf("ZEROCLEAR"), "ZeroT" to emptyList(),
        "Zeus Panda" to emptyList(), "ZIPLINE" to emptyList(), "ZLib" to emptyList(),
        "Zox" to listOf("Gresim", "ZoxRPC", "ZoxPNG"), "zwShell" to emptyList(),
        "ZxShell" to listOf("Sensocode"), "ZxxZ" to emptyList(),
    )

    val KNOWN_THREAT_ACTORS: Map<String, String> = buildLookup(threatActorData)
    val KNOWN_SOFTWARE: Map<String, String> = buildLookup(softwareData)
}
