package com.threatloom.app.ui.components

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.unit.dp

@Composable
fun LlmDisclaimer(modifier: Modifier = Modifier) {
    Text(
        text = "This summary was generated by Threat Loom using large language models (LLMs). LLMs can make mistakes. Always verify important information against the original source.",
        style = MaterialTheme.typography.bodySmall,
        fontStyle = FontStyle.Italic,
        color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f),
        modifier = modifier.fillMaxWidth().padding(top = 12.dp)
    )
}
